name: buildbot
on:
  workflow_dispatch:
  push:
jobs:
  buildbot:
    runs-on: ubuntu-24.04
    steps:
      - name: Setup Toolchain
        id: setup-toolchain
        uses: skiptools/swift-android-action@main
        with:
          # just set up the toolchain and don't build anything
          build-package: false

      - name: Build packages
        shell: bash
        run: |
          set -x
          # random selection of the swiftpackageindex repositories
          for REPO in $(curl https://raw.githubusercontent.com/SwiftPackageIndex/PackageList/refs/heads/main/packages.json | jq -r '.[]' | sort -R) ; do
            echo "Building repository: ${REPO}"

            DIR=$(echo "${REPO}" | cut -f 4- -d '/' | sed 's;.git$;;g')
            mkdir -p ${DIR}
            cd ${DIR}
            git clone https://github.com/${REPO} .
            ${{ steps.setup-toolchain.outputs.swift-build }} -c debug
            exit 0
          done

